jenkins:
  build: .
  privileged: true
  ports:
    - "8080:8080"
    - "50000:50000"
    - "8000:8000"
  volumes:
    - ./jenkins_home:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
